/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ApiAdminRouteImport } from './routes/api/admin'
import { Route as ApiControlRouteImport } from './routes/api/control'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiSetupSplatRouteImport } from './routes/api/setup/$'
import { Route as ApiUpstreamOauthCallbackRouteImport } from './routes/api/upstream-oauth/callback'
import { Route as ApiUpstreamOauthStartRouteImport } from './routes/api/upstream-oauth/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiControlRoute = ApiControlRouteImport.update({
  id: '/api/control',
  path: '/api/control',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupSplatRoute = ApiSetupSplatRouteImport.update({
  id: '/api/setup/$',
  path: '/api/setup/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpstreamOauthCallbackRoute =
  ApiUpstreamOauthCallbackRouteImport.update({
    id: '/api/upstream-oauth/callback',
    path: '/api/upstream-oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUpstreamOauthStartRoute = ApiUpstreamOauthStartRouteImport.update({
  id: '/api/upstream-oauth/start',
  path: '/api/upstream-oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/mcp': typeof McpRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/control': typeof ApiControlRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/setup/$': typeof ApiSetupSplatRoute
  '/api/upstream-oauth/callback': typeof ApiUpstreamOauthCallbackRoute
  '/api/upstream-oauth/start': typeof ApiUpstreamOauthStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/mcp': typeof McpRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/control': typeof ApiControlRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/setup/$': typeof ApiSetupSplatRoute
  '/api/upstream-oauth/callback': typeof ApiUpstreamOauthCallbackRoute
  '/api/upstream-oauth/start': typeof ApiUpstreamOauthStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/mcp': typeof McpRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/control': typeof ApiControlRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/setup/$': typeof ApiSetupSplatRoute
  '/api/upstream-oauth/callback': typeof ApiUpstreamOauthCallbackRoute
  '/api/upstream-oauth/start': typeof ApiUpstreamOauthStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/mcp'
    | '/api/admin'
    | '/api/control'
    | '/oauth/consent'
    | '/api/auth/$'
    | '/api/setup/$'
    | '/api/upstream-oauth/callback'
    | '/api/upstream-oauth/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/mcp'
    | '/api/admin'
    | '/api/control'
    | '/oauth/consent'
    | '/api/auth/$'
    | '/api/setup/$'
    | '/api/upstream-oauth/callback'
    | '/api/upstream-oauth/start'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/mcp'
    | '/api/admin'
    | '/api/control'
    | '/oauth/consent'
    | '/api/auth/$'
    | '/api/setup/$'
    | '/api/upstream-oauth/callback'
    | '/api/upstream-oauth/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  McpRoute: typeof McpRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiControlRoute: typeof ApiControlRoute
  OauthConsentRoute: typeof OauthConsentRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSetupSplatRoute: typeof ApiSetupSplatRoute
  ApiUpstreamOauthCallbackRoute: typeof ApiUpstreamOauthCallbackRoute
  ApiUpstreamOauthStartRoute: typeof ApiUpstreamOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/control': {
      id: '/api/control'
      path: '/api/control'
      fullPath: '/api/control'
      preLoaderRoute: typeof ApiControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup/$': {
      id: '/api/setup/$'
      path: '/api/setup/$'
      fullPath: '/api/setup/$'
      preLoaderRoute: typeof ApiSetupSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upstream-oauth/callback': {
      id: '/api/upstream-oauth/callback'
      path: '/api/upstream-oauth/callback'
      fullPath: '/api/upstream-oauth/callback'
      preLoaderRoute: typeof ApiUpstreamOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upstream-oauth/start': {
      id: '/api/upstream-oauth/start'
      path: '/api/upstream-oauth/start'
      fullPath: '/api/upstream-oauth/start'
      preLoaderRoute: typeof ApiUpstreamOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  McpRoute: McpRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiControlRoute: ApiControlRoute,
  OauthConsentRoute: OauthConsentRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSetupSplatRoute: ApiSetupSplatRoute,
  ApiUpstreamOauthCallbackRoute: ApiUpstreamOauthCallbackRoute,
  ApiUpstreamOauthStartRoute: ApiUpstreamOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
